apiVersion: v1
baseDomain: okd.local
metadata:
  name: lab
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: 'insert_pull_secret'
sshKey: 'insert_ssh_public_key'
apiVersion: v1
baseDomain: okd.local
compute: 
- hyperthreading: Enabled 
  name: worker
  replicas: 4 
controlPlane: 
  hyperthreading: Enabled 
  name: master
  replicas: 3 
metadata:
  name: lab
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OVNKubernetes
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2FrYXJvbnRlMXR2YWp1ZHpjaW0zYWhub2gzdGdjeXlhdnZvOlBEU0tESEIxTzdTODI4MVBRRUxYRFdSVjZHTDJTNk0yMzFJNThUVE1NMElJVEpQM01CWDNaQU42Wk5STDlMTjU=","email":"adriandepalma@hotmail.es"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2FrYXJvbnRlMXR2YWp1ZHpjaW0zYWhub2gzdGdjeXlhdnZvOlBEU0tESEIxTzdTODI4MVBRRUxYRFdSVjZHTDJTNk0yMzFJNThUVE1NMElJVEpQM01CWDNaQU42Wk5STDlMTjU=","email":"adriandepalma@hotmail.es"},"registry.connect.redhat.com":{"auth":"ODE1MzE4MHx1aGMtMVR2QWp1RFpjaU0zQWhOT0gzVGdjWVlhVlZPOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lJM05qSmhNRE14Wm1Wak9XVTBZMk14WWpjM09EZzNZVGsyTVRabFpHVXdZU0o5Lm5ZWlZCOXNLcUlBVWl3Y0pFMDVhTGItb0dyU2hHX0hYb3E4SGpsV0NaUlBQT1FLeHBQY1FPQlRkb04yY2VGSWZ1OU81NGZsdGxzcC1SOTZaaUZ4Z29YNUR5SnQ4d3g3aW11N3VVWlR0ZzdieXlVcEZySDVRVVBpaEFHYk9SOUhzdWlWSzFob3g0a3F6dGpJbFRkX0RadUJtV0FZUDZFbm9vZXdkTWdOZndNTjIzUEV2SlhrcGNSWnR2NnRNN3VLV3RnclJVZWljMzV1V05HZGlFYndoUWdnYlRlbjlYbnZnUVBkVUs1cy1RMWFTeHZDbllhTE9PYTAyQ0phSEgyX3hLS3diTllMUE90U19kV2I4TVZrNE9SMEpZTDdRRnREdkt4anZYeVY0TzVnVWhTNGJ3YkJXMFMyOFlzalpxX19zRGUzbDRKSEhkU2h5TEhiSlVjWnVIaUtaNU9PZllLWXhaVGFRaGxpQWVuQ2tDRDg5V3kwQ2NERXYwWlpWaGxoR29FcVR2WThxalB0SWl3UlNBWU5mQ0p4Q043X3l3ZGRHUDV2ZGdYVE5VLXBYRnhsSjVzR1RtOXRlNG8xbmtsN3o0SWlwUlFvd2NFRTJyZl9IYUJ0VWNxVWFkOGN6cy15SHpEZjRpQTVESV9zcGM3R29taHFOdHVaQlY4X3dCcThhZDNwTFZab1VEYk83a0JCcEgxcDZ3T185emN3VHduTC1SSHJCQ3lWQjlHcnFKbkIzZmN2VWE5cjdaT2xwQ0lTbmxlc2VKdTIwMDNQNUNLUEtJSXhtR1o5ZG10VWt6dEVGT2dEd3JMeVpZV09KMFRJX2tEOXROUGhSa3gyMzh5cnFKbzQ3ZVBuWHZvQlV5QUNkdDJPY3NvaXE5djFiaGxPTHgwdUM0V0dyNFhB","email":"adriandepalma@hotmail.es"},"registry.redhat.io":{"auth":"ODE1MzE4MHx1aGMtMVR2QWp1RFpjaU0zQWhOT0gzVGdjWVlhVlZPOmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lJM05qSmhNRE14Wm1Wak9XVTBZMk14WWpjM09EZzNZVGsyTVRabFpHVXdZU0o5Lm5ZWlZCOXNLcUlBVWl3Y0pFMDVhTGItb0dyU2hHX0hYb3E4SGpsV0NaUlBQT1FLeHBQY1FPQlRkb04yY2VGSWZ1OU81NGZsdGxzcC1SOTZaaUZ4Z29YNUR5SnQ4d3g3aW11N3VVWlR0ZzdieXlVcEZySDVRVVBpaEFHYk9SOUhzdWlWSzFob3g0a3F6dGpJbFRkX0RadUJtV0FZUDZFbm9vZXdkTWdOZndNTjIzUEV2SlhrcGNSWnR2NnRNN3VLV3RnclJVZWljMzV1V05HZGlFYndoUWdnYlRlbjlYbnZnUVBkVUs1cy1RMWFTeHZDbllhTE9PYTAyQ0phSEgyX3hLS3diTllMUE90U19kV2I4TVZrNE9SMEpZTDdRRnREdkt4anZYeVY0TzVnVWhTNGJ3YkJXMFMyOFlzalpxX19zRGUzbDRKSEhkU2h5TEhiSlVjWnVIaUtaNU9PZllLWXhaVGFRaGxpQWVuQ2tDRDg5V3kwQ2NERXYwWlpWaGxoR29FcVR2WThxalB0SWl3UlNBWU5mQ0p4Q043X3l3ZGRHUDV2ZGdYVE5VLXBYRnhsSjVzR1RtOXRlNG8xbmtsN3o0SWlwUlFvd2NFRTJyZl9IYUJ0VWNxVWFkOGN6cy15SHpEZjRpQTVESV9zcGM3R29taHFOdHVaQlY4X3dCcThhZDNwTFZab1VEYk83a0JCcEgxcDZ3T185emN3VHduTC1SSHJCQ3lWQjlHcnFKbkIzZmN2VWE5cjdaT2xwQ0lTbmxlc2VKdTIwMDNQNUNLUEtJSXhtR1o5ZG10VWt6dEVGT2dEd3JMeVpZV09KMFRJX2tEOXROUGhSa3gyMzh5cnFKbzQ3ZVBuWHZvQlV5QUNkdDJPY3NvaXE5djFiaGxPTHgwdUM0V0dyNFhB","email":"adriandepalma@hotmail.es"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDD+yYW9UZVYtnKFSWQjDeYMLVHpX7zGDzBAHiXbM4VSz8ClGypJmbO82cOSG3L8Idur4TVliJw8fEJoI3kCgpfSILhp9gfe/HgHL3T2gF+R3gUruIRnD6ki8EA2CjjCtTX+lgt3xbRlmeuwtjtf6qs6Xfh1dWS+va0obCn5t92D7egvMR+II4xaKrppPI9urK6VN2KbgsxnSy7gwbFWJxP40mwliIdsqRWX6pWGONkYXTkrZQTrQprjuXYnad6ZAUSsWpCcKrlYVqk8Lw88HoBmcP6SevNCDrH6GuS2V75Hf4HaqvGP2PPGasT3j/5hlgcIZdR2X6mHKrLL7e0fxp root@okd4-services.okd.local'
capabilities:
  baselineCapabilitySet: None
  additionalEnabledCapabilities:
  - openshift-samples